import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/src/shared/auth/auth-provider";
import { NotificationProvider } from "@/src/shared/ui/Notifications";
import { UnreadProvider } from "@/src/entities/chat";
import { MeProvider } from "@/src/entities/user";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={inter.variable}
      style={{ height: "100%" }}
    >
      <body>
        <NotificationProvider>
          <AuthProvider>
            <MeProvider>
              <UnreadProvider>{children}</UnreadProvider>
            </MeProvider>
          </AuthProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
